In [1]:
import os
import cv2

def images_to_video(image_folder, output_video_path, fps=30):
    image_files = [f for f in os.listdir(image_folder) if f.endswith('.jpg') or f.endswith('.png')]
    image_files.sort()

    if not image_files:
        print("No image files found in the folder.")
        return

    frame = cv2.imread(os.path.join(image_folder, image_files[0]))
    height, width, layers = frame.shape

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    for image_file in image_files:
        image_path = os.path.join(image_folder, image_file)
        frame = cv2.imread(image_path)
        video.write(frame)

    video.release()
    cv2.destroyAllWindows()

# Provide the path to the folder containing your images and the desired output video path
images_folder = '/mnt/DATA/macrohet/NDX_animation_dev/ND0000.2.10'
output_video_path = '/mnt/DATA/macrohet/NDX_animation_dev/ND0000.2.10.mp4'
images_to_video(images_folder, output_video_path)


error: OpenCV(4.8.0) /io/opencv/modules/highgui/src/window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'


In [9]:
import napari
from skimage import io
from natsort import natsorted
import numpy as np
import glob
from tqdm.auto import tqdm

In [10]:
image_stack = np.stack([io.imread(fn) for fn in tqdm(natsorted(glob.glob(os.path.join(images_folder, '*.png'))))], axis = 0)

  0%|          | 0/376 [00:00<?, ?it/s]

In [11]:
v = napari.Viewer()
v.add_image(image_stack)

<Image layer 'image_stack' at 0x7fe50b448220>

# Moving files locally to see if that speeds up image IO times

In [12]:
base_dir = '/run/user/30046150/gvfs/smb-share:server=data2.thecrick.org,share=lab-gutierrezm/home/users/dayn/macrohet_nemo/macrohet_images/NDXXXX_optimisation/ND0000__2023-08-04T15_27_41-Measurement 1/'

In [13]:
image_dir = os.path.join(base_dir, 'Images')

In [23]:
import shutil
from macrohet import dataio, tile, visualise


In [24]:
# base_dir = '/mnt/DATA/macrohet/'
base_dir = '/run/user/30046150/gvfs/smb-share:server=data2.thecrick.org,share=lab-gutierrezm/home/users/dayn/macrohet_nemo/macrohet_images/NDXXXX_optimisation/ND0000__2023-08-04T15_27_41-Measurement 1/'
# base_dir = '/Volumes/lab-gutierrezm/home/users/dayn/macrohet_nemo/macrohet_images/NDXXXX_optimisation/ND0000__2023-08-04T15_27_41-Measurement 1/'
# metadata_fn = os.path.join(base_dir, 'macrohet_images/Index.idx.xml')
metadata_fn = os.path.join(base_dir, 'Images/Index.idx.xml')
metadata = dataio.read_harmony_metadata(metadata_fn)  
metadata

Reading metadata XML file...


Extracting HarmonyV5 metadata:   0%|          | 0/243648 [00:00<?, ?it/s]

Extracting metadata complete!


id State                               URL Row Col  \
0         0203K1F1P1R1    Ok    r02c03f01p01-ch1sk1fk1fl1.tiff   2   3   
1         0203K1F1P1R2    Ok    r02c03f01p01-ch2sk1fk1fl1.tiff   2   3   
2         0203K1F1P1R3    Ok    r02c03f01p01-ch3sk1fk1fl1.tiff   2   3   
3         0203K1F1P2R1    Ok    r02c03f01p02-ch1sk1fk1fl1.tiff   2   3   
4         0203K1F1P2R2    Ok    r02c03f01p02-ch2sk1fk1fl1.tiff   2   3   
...                ...   ...                               ...  ..  ..   
243643  0310K376F9P2R2    Ok  r03c10f09p02-ch2sk376fk1fl1.tiff   3  10   
243644  0310K376F9P2R3    Ok  r03c10f09p02-ch3sk376fk1fl1.tiff   3  10   
243645  0310K376F9P3R1    Ok  r03c10f09p03-ch1sk376fk1fl1.tiff   3  10   
243646  0310K376F9P3R2    Ok  r03c10f09p03-ch2sk376fk1fl1.tiff   3  10   
243647  0310K376F9P3R3    Ok  r03c10f09p03-ch3sk376fk1fl1.tiff   3  10   

       FieldID PlaneID TimepointID ChannelID FlimID  ... PositionZ  \
0            1       1           0         1      1  ...         0   
1            1       1           0         2      1  ...         0   
2            1       1           0         3      1  ...         0   
3            1       2           0         1      1  ...     2E-06   
4            1       2           0         2      1  ...     2E-06   
...        ...     ...         ...       ...    ...  ...       ...   
243643       9       2         375         2      1  ...     2E-06   
243644       9       2         375         3      1  ...     2E-06   
243645       9       3         375         1      1  ...     4E-06   
243646       9       3         375         2      1  ...     4E-06   
243647       9       3         375         3      1  ...     4E-06   

       AbsPositionZ MeasurementTimeOffset                        AbsTime  \
0       0.135205805                     0    2023-08-04T15:28:16.5+01:00   
1       0.135205805                     0    2023-08-04T15:28:16.5+01:00   
2       0.135205805                     0  2023-08-04T15:28:16.767+01:00   
3       0.135207802                     0  2023-08-04T15:28:17.047+01:00   
4       0.135207802                     0  2023-08-04T15:28:17.047+01:00   
...             ...                   ...                            ...   
243643  0.135064006            337503.973  2023-08-08T13:15:47.533+01:00   
243644  0.135064006            337503.973    2023-08-08T13:15:47.8+01:00   
243645  0.135066003            337503.973   2023-08-08T13:15:48.08+01:00   
243646  0.135066003            337503.973  2023-08-08T13:15:48.097+01:00   
243647  0.135066003            337503.973   2023-08-08T13:15:48.36+01:00   

       MainExcitationWavelength MainEmissionWavelength ObjectiveMagnification  \
0                           561                    599                     40   
1                           740                      0                     40   
2                           640                    706                     40   
3                           561                    599                     40   
4                           740                      0                     40   
...                         ...                    ...                    ...   
243643                      740                      0                     40   
243644                      640                    706                     40   
243645                      561                    599                     40   
243646                      740                      0                     40   
243647                      640                    706                     40   

       ObjectiveNA ExposureTime  \
0              1.1          0.2   
1              1.1          0.2   
2              1.1          0.2   
3              1.1          0.2   
4              1.1          0.2   
...            ...          ...   
243643         1.1          0.2   
243644         1.1          0.2   
243645         1.1          0.2   
243646         1.1          0.2   
243647         1.1 

In [28]:
image_fns = [os.path.join(image_dir, fn) for fn in metadata['URL'].values if 'r02c10' in fn]

In [45]:
len(image_fns)*9

274104

In [49]:
for fn in tqdm(image_fns):
    new_fn = fn.replace(image_dir, '/mnt/DATA/macrohet/macrohet_images/ND0000/Images')
    if os.path.exists(new_fn):
        continue
    shutil.copy(fn, new_fn)

  0%|          | 0/30456 [00:00<?, ?it/s]

In [47]:
io.imread('/run/user/30046150/gvfs/smb-share:server=data2.thecrick.org,share=lab-gutierrezm/home/users/dayn/macrohet_nemo/macrohet_images/NDXXXX_optimisation/ND0000__2023-08-04T15_27_41-Measurement 1/Images/r02c10f07p02-ch1sk119fk1fl1.tiff')

array([[1692, 1730, 1789, ...,  122,  117,  118],
       [1787, 1853, 1903, ...,  113,  115,  117],
       [1963, 2024, 2033, ...,  114,  121,  123],
       ...,
       [ 117,  110,  109, ...,  106,  113,  118],
       [ 114,  117,  117, ...,  109,  113,  112],
       [ 119,  123,  126, ...,  111,  109,  112]], dtype=uint16)

In [37]:
io.imread('/mnt/DATA/macrohet/macrohet_images/ND0000/Images/r02c10f01p01-ch1sk1fk1fl1.tiff')

array([[ 216,  223,  216, ...,  121,  102,  114],
       [ 220,  217,  222, ...,  118,  109,  122],
       [ 214,  207,  217, ...,  120,  122,  126],
       ...,
       [ 129,  130,  125, ..., 1090,  997,  881],
       [ 132,  138,  130, ..., 1068,  990,  905],
       [ 133,  141,  129, ..., 1071, 1003,  881]], dtype=uint16)

In [38]:
io.imread('/mnt/DATA/macrohet/macrohet_images/PS0000/Images/r03c07f01p01-ch1sk1fk1fl1.tiff')

array([[104, 106, 103, ..., 340, 333, 319],
       [107, 106,  98, ..., 346, 350, 315],
       [105, 106, 107, ..., 369, 343, 319],
       ...,
       [635, 637, 657, ..., 114, 111, 109],
       [639, 653, 670, ..., 108, 106,  98],
       [652, 629, 669, ..., 103, 110, 109]], dtype=uint16)

In [42]:
file_size_bytes = os.path.getsize('/mnt/DATA/macrohet/macrohet_images/ND0000/Images/r02c10f01p01-ch1sk1fk1fl1.tiff')
file_size_kb = file_size_bytes / 1024  # Convert bytes to kilobytes
file_size_mb = file_size_kb / 1024 
print(file_size_mb)

8.601713180541992


In [41]:
file_size_bytes = os.path.getsize('/mnt/DATA/macrohet/macrohet_images/PS0000/Images/r03c07f01p01-ch1sk1fk1fl1.tiff')
file_size_kb = file_size_bytes / 1024  # Convert bytes to kilobytes
file_size_mb = file_size_kb / 1024 
print(file_size_mb)

8.1167631149292
